version: "3"
services:
  gitlab-ce:
    image: gitlab/gitlab-ce
    container_name: gitlab-ce
    hostname: 'localhost'
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - type: bind
        source: ./gitlab-ce/config
        target: /etc/gitlab
      - type: bind
        source: ./gitlab-ce/logs
        target: /var/log/gitlab
      - type: bind
        source: ./gitlab-ce/data
        target: /var/opt/gitlab
  